name: math-4025-sp26
channels:
  - conda-forge
dependencies:
  - _openmp_mutex=4.5
  - _python_abi3_support=1.0
  - anyio=4.12.1
  - argon2-cffi=25.1.0
  - argon2-cffi-bindings=25.1.0
  - arrow=1.4.0
  - asttokens=3.0.1
  - async-lru=2.1.0
  - attr=2.5.2
  - attrs=25.4.0
  - autograd=1.8.0
  - autograd-gamma=0.5.0
  - babel=2.17.0
  - backports.zstd=1.3.0
  - beautifulsoup4=4.14.3
  - bleach=6.3.0
  - bleach-with-css=6.3.0
  - brotli=1.2.0
  - brotli-bin=1.2.0
  - brotli-python=1.2.0
  - bzip2=1.0.8
  - ca-certificates=2026.1.4
  - cached-property=1.5.2
  - cached_property=1.5.2
  - certifi=2026.1.4
  - cffi=2.0.0
  - charset-normalizer=3.4.4
  - comm=0.2.3
  - contourpy=1.3.3
  - cpython=3.14.2
  - cuda-crt-tools=13.1.115
  - cuda-cudart=13.1.80
  - cuda-cudart_linux-64=13.1.80
  - cuda-cuobjdump=13.1.115
  - cuda-cupti=13.1.115
  - cuda-nvcc-tools=13.1.115
  - cuda-nvdisasm=13.1.115
  - cuda-nvrtc=13.1.115
  - cuda-nvtx=13.1.115
  - cuda-nvvm-tools=13.1.115
  - cuda-version=13.1
  - cycler=0.12.1
  - debugpy=1.8.20
  - decorator=5.2.1
  - defusedxml=0.7.1
  - exceptiongroup=1.3.1
  - executing=2.2.1
  - filelock=3.20.3
  - fmt=12.1.0
  - fonttools=4.61.1
  - formulaic=1.2.1
  - fqdn=1.5.1
  - freetype=2.14.1
  - fsspec=2026.1.0
  - future=1.0.0
  - gmp=6.3.0
  - gmpy2=2.2.1
  - h11=0.16.0
  - h2=4.3.0
  - hpack=4.1.0
  - httpcore=1.0.9
  - httpx=0.28.1
  - hyperframe=6.1.0
  - icu=78.2
  - idna=3.11
  - importlib-metadata=8.7.0
  - importlib_resources=6.5.2
  - interface_meta=1.3.0
  - ipykernel=7.1.0
  - ipython=9.10.0
  - ipython_pygments_lexers=1.1.1
  - ipywidgets=8.1.8
  - islp=0.4.0
  - isoduration=20.11.0
  - itables=2.6.2
  - jedi=0.19.2
  - jinja2=3.1.6
  - joblib=1.5.3
  - json5=0.13.0
  - jsonpointer=3.0.0
  - jsonschema=4.26.0
  - jsonschema-specifications=2025.9.1
  - jsonschema-with-format-nongpl=4.26.0
  - jupyter=1.1.1
  - jupyter-lsp=2.3.0
  - jupyter_client=8.8.0
  - jupyter_console=6.6.3
  - jupyter_core=5.9.1
  - jupyter_events=0.12.0
  - jupyter_server=2.17.0
  - jupyter_server_terminals=0.5.4
  - jupyterlab=4.5.3
  - jupyterlab_pygments=0.3.0
  - jupyterlab_server=2.28.0
  - jupyterlab_widgets=3.0.16
  - keyutils=1.6.3
  - kiwisolver=1.4.9
  - krb5=1.22.2
  - lark=1.3.1
  - lcms2=2.18
  - ld_impl_linux-64=2.45
  - lerc=4.0.0
  - libabseil=20250512.1
  - libblas=3.11.0
  - libbrotlicommon=1.2.0
  - libbrotlidec=1.2.0
  - libbrotlienc=1.2.0
  - libcap=2.77
  - libcblas=3.11.0
  - libcublas=13.2.1.1
  - libcudnn=9.18.0.77
  - libcudss=0.7.1.4
  - libcufft=12.1.0.78
  - libcufile=1.16.1.26
  - libcurand=10.4.1.81
  - libcusolver=12.0.9.81
  - libcusparse=12.7.3.1
  - libdeflate=1.25
  - libedit=3.1.20250104
  - libexpat=2.7.3
  - libffi=3.5.2
  - libfreetype=2.14.1
  - libfreetype6=2.14.1
  - libgcc=15.2.0
  - libgcc-ng=15.2.0
  - libgfortran=15.2.0
  - libgfortran5=15.2.0
  - libiconv=1.18
  - libjpeg-turbo=3.1.2
  - liblapack=3.11.0
  - liblzma=5.8.2
  - libmagma=2.9.0
  - libmpdec=4.0.0
  - libnl=3.11.0
  - libnvjitlink=13.1.115
  - libopenblas=0.3.30
  - libpng=1.6.54
  - libprotobuf=6.31.1
  - libsodium=1.0.18
  - libsqlite=3.51.2
  - libstdcxx=15.2.0
  - libstdcxx-ng=15.2.0
  - libsystemd0=258.3
  - libtiff=4.7.1
  - libtorch=2.10.0
  - libudev1=258.3
  - libuuid=2.41.3
  - libuv=1.51.0
  - libwebp-base=1.6.0
  - libxcb=1.17.0
  - libxml2=2.15.1
  - libxml2-16=2.15.1
  - libxslt=1.1.43
  - libzlib=1.3.1
  - lifelines=0.30.0
  - lightning-utilities=0.15.2
  - llvm-openmp=21.1.8
  - lxml=6.0.2
  - markupsafe=3.0.3
  - matplotlib-base=3.10.8
  - matplotlib-inline=0.2.1
  - mistune=3.2.0
  - mizani=0.14.4
  - mpc=1.3.1
  - mpfr=4.2.1
  - mpmath=1.3.0
  - munkres=1.1.4
  - narwhals=2.16.0
  - nbclient=0.10.4
  - nbconvert-core=7.17.0
  - nbformat=5.10.4
  - nccl=2.29.2.1
  - ncurses=6.5
  - nest-asyncio=1.6.0
  - networkx=3.6.1
  - nomkl=1.0
  - notebook=7.5.3
  - notebook-shim=0.2.4
  - numpy=2.4.2
  - openjpeg=2.5.4
  - openssl=3.6.1
  - optree=0.18.0
  - overrides=7.7.0
  - packaging=26.0
  - pandas=3.0.0
  - pandocfilters=1.5.0
  - parso=0.8.5
  - patsy=1.0.2
  - pexpect=4.9.0
  - pillow=12.1.0
  - pip=26.0
  - platformdirs=4.5.1
  - plotnine=0.15.3
  - progressbar2=4.5.0
  - prometheus_client=0.24.1
  - prompt-toolkit=3.0.52
  - prompt_toolkit=3.0.52
  - psutil=7.2.2
  - pthread-stubs=0.4
  - ptyprocess=0.7.0
  - pure_eval=0.2.3
  - pybind11=3.0.1
  - pybind11-abi=11
  - pybind11-global=3.0.1
  - pycparser=2.22
  - pygam=0.12.0
  - pygments=2.19.2
  - pyparsing=3.3.2
  - pyreadr=0.5.4
  - pysocks=1.7.1
  - python=3.14.2
  - python-dateutil=2.9.0.post0
  - python-fastjsonschema=2.21.2
  - python-gil=3.14.2
  - python-json-logger=2.0.7
  - python-tzdata=2025.3
  - python-utils=3.9.1
  - python_abi=3.14
  - pytorch=2.10.0
  - pytorch-lightning=2.6.1
  - pytz=2025.2
  - pyyaml=6.0.3
  - pyzmq=27.1.0
  - qhull=2020.2
  - rdma-core=61.0
  - readline=8.3
  - referencing=0.37.0
  - requests=2.32.5
  - rfc3339-validator=0.1.4
  - rfc3986-validator=0.1.1
  - rfc3987-syntax=1.1.0
  - rpds-py=0.30.0
  - scikit-learn=1.8.0
  - scikit-misc=0.5.2
  - scipy=1.17.0
  - seaborn=0.13.2
  - seaborn-base=0.13.2
  - send2trash=2.1.0
  - setuptools=80.10.2
  - six=1.17.0
  - sleef=3.9.0
  - sniffio=1.3.1
  - soupsieve=2.8.3
  - stack_data=0.6.3
  - statsmodels=0.14.6
  - sympy=1.14.0
  - tabulate=0.9.0
  - terminado=0.18.1
  - threadpoolctl=3.6.0
  - tinycss2=1.5.1
  - tk=8.6.13
  - tomli=2.4.0
  - torchmetrics=1.8.2
  - tornado=6.5.4
  - tqdm=4.67.2
  - traitlets=5.14.3
  - triton=3.6.0
  - typing-extensions=4.15.0
  - typing_extensions=4.15.0
  - typing_utils=0.1.0
  - tzdata=2025c
  - unicodedata2=17.0.0
  - uri-template=1.3.0
  - urllib3=2.6.3
  - wcwidth=0.5.3
  - webcolors=25.10.0
  - webencodings=0.5.1
  - websocket-client=1.9.0
  - widgetsnbextension=4.0.15
  - wrapt=2.1.1
  - xorg-libxau=1.0.12
  - xorg-libxdmcp=1.1.5
  - yaml=0.2.5
  - zeromq=4.3.5
  - zipp=3.23.0
  - zlib-ng=2.3.2
  - zstd=1.5.7
  - pip:
      - pyhere==1.0.3
prefix: /home/efriedlander/miniforge3/envs/math-4025-sp26
